README.md

The wrong hooks was being used in the useLiveQuery example.

Fixes an error in the live query example

---

package.json
src/queries/usePendingCursorOperation.spec.tsx
src/queries/usePendingCursorOperation.tsx

We need developers to be able to reset live queries on the pending cursor operation hook. 
An example where this is useful is for example when you have a live query with a `limit`, eg: 
```ts
const { documents } = usePendingCursorOperation({ collection: 'foo', limit: 1 })
const hasDocuments = !!documents.length
```
In this case if the document returned by the live query is deleted, the Ditto SDK will not return null and instead simply return an empty an empty array of documents, which can lead to the misinterpretation of the collection being empty. 
The only way to refresh the `documents` result such that the query is relaunched, and a different document from the store can be used as a sentinel of documents existing in the store, is by resetting the current live query.

Adds a reset function to the pending cursor operation.

---

karma.conf.js
package.json
src/DittoLazyProvider.spec.tsx
src/DittoLazyProvider.tsx
src/DittoProvider.spec.tsx
src/DittoProvider.tsx
src/mutations/useMutations.spec.tsx
src/queries/useCollections.spec.tsx
src/queries/usePendingCursorOperation.spec.tsx
src/queries/usePendingCursorOperation.tsx
src/queries/usePendingIDSpecificOperation.spec.tsx
src/queries/usePendingIDSpecificOperation.tsx
src/useDitto.ts
src/utils.spec.ts

Fixes a bug on the tests by adding a custom built waitFor function for DOM assertions. The old version was not waiting for the React components to stabilize and this was leading to flaky tests.

Fixes the loading state on the eager Ditto Provider.

---

src/mutations/useMutations.ts
src/queries/useLazyPendingCursorOperation.ts
src/queries/useLazyPendingIDSpecificOperation.ts
src/queries/usePendingCursorOperation.ts
src/queries/usePendingIDSpecificOperation.ts

@konstantinbe said that we should be returning `DocumentLike` from the `usePendingCursorOperation`  and `usePendingIDSpecificOperations`

Problem: cursor hooks should return `DocumentLike` not `Document`

---

src/queries/useLazyPendingCursorOperation.spec.tsx
src/queries/useLazyPendingCursorOperation.ts
src/queries/useLazyPendingIDSpecificOperation.spec.tsx
src/queries/useLazyPendingIDSpecificOperation.ts
src/queries/usePendingCursorOperation.spec.tsx
src/queries/usePendingCursorOperation.ts
src/queries/usePendingIDSpecificOperation.spec.tsx
src/queries/usePendingIDSpecificOperation.ts

The react ditto library has no way pass down local only live queries to the `usePendingCursorOperation` and `usePendingIDSpecificOperation` hooks. 
Add an optional param called `localOnly` which takes a boolean. If omitted, it will be `false`. If `true`, then the live query will only run on local data mutations and will not replicate
```ts
usePendingCursorOperation({ 
localOnly: true // if omitted this will be false
})
```

Hooks for queries and cursors are missing a "local" param

---

examples/create-react-app-typescript-example/src/App.tsx
package.json
src/mutations/useMutations.spec.tsx
src/mutations/useMutations.ts
src/queries/useCollections.ts
src/queries/useLazyPendingIDSpecificOperation.spec.tsx
src/queries/usePendingIDSpecificOperation.spec.tsx
src/queries/usePendingIDSpecificOperation.ts
yarn.lock

Upgrades the SDK to version 1.0.17 where the DocumentID type no longer exists.

SDK 1.0.17 upgrade

---

src/DittoContext.tsx
src/DittoLazyProvider.spec.tsx
src/DittoProvider.spec.tsx
src/queries/useLazyPendingCursorOperation.ts
src/queries/useLazyPendingIDSpecificOperation.ts
src/useDitto.ts

Introduces a simple `useDittoContext` wrapper to be used in favor of `useContext(DittoContext)`
Gives the added benefit of custom error messaging when user is attempting to consume the context without the required context provider. Improves code reusability.

Introduce useDittoContext hook

---

package.json
src/DittoLazyProvider.spec.tsx
src/DittoLazyProvider.tsx
src/queries/useCollections.spec.tsx
src/queries/useLazyPendingCursorOperation.spec.tsx
src/queries/useLazyPendingIDSpecificOperation.spec.tsx
src/queries/usePendingCursorOperation.spec.tsx
src/queries/usePendingIDSpecificOperation.spec.tsx
src/queries/usePendingIDSpecificOperation.ts
yarn.lock

The previous implementation could cause multiple ditto instances belonging to the same path to be created if the load function was called multiple times before the setDittoHash render cycle kicked in. We now maintain a ref with all the paths that have been created, in order to immediately track the path for which a Ditto instance has been created or is in the process of being created.
The SDK dependency has been updated, and some tests have been optinised to make them more robust.

Optimizes the DittoLazyProvider for concurrent instance creation.

---

.github/workflows/ci.yml

[This commit](https://github.com/getditto/react-ditto/commit/4af0738dc44a073efb3086348fa3986d0821ee8f) pushed to a branch different from `master` triggered [an update to the docs](https://github.com/getditto/react-ditto/commit/8f942ebb7a16f36f5100348fed0ed47bd15d4825).
We should only deploy docs from `master`. The [CI run](https://github.com/getditto/react-ditto/runs/5774652684) for this PR's branch successfully skipped that build step.

Only deploy docs on pushes to master

---

README.md
examples/create-react-app-typescript-example/src/AppContainer.tsx
examples/create-react-app-typescript-example/src/AuthenticationPanel.tsx
package.json
src/identity/useOnlineIdentity.spec.tsx
src/identity/useOnlineIdentity.ts
yarn.lock

Authentication needs to be done through the  instance using the ditto.auth.login functions. This PR removes  `authenticate` from `useOnlineIdenty` and updates the internal implementation of getAuthenticationRequired and getTokenExpiresInSeconds.
This fixes a bug whereby calls to `authenticate` were only reporting errors the first time authenticate was called and not in subsequent calls.

Removes the authentication function from the useOnlineIdentity hook

---

README.md
examples/create-react-app-typescript-example/src/App.tsx
package.json
src/DittoLazyProvider.spec.tsx
src/DittoProvider.spec.tsx
src/mutations/useMutations.spec.tsx
src/mutations/useMutations.ts
src/queries/useCollections.spec.tsx
src/queries/useLazyPendingCursorOperation.spec.tsx
src/queries/useLazyPendingIDSpecificOperation.spec.tsx
src/queries/usePendingCursorOperation.spec.tsx
src/queries/usePendingIDSpecificOperation.spec.tsx
yarn.lock

Related issue: #27
Versions of `@dittolive/ditto` compatible with v1.1.10 are now allowed as a peer dependency. Besides removing `insert` in favor of `upsert`, `InsertParams` and `InsertFunction` have also been dropped in favor of `UpsertParams` and `UpsertFunction`, respectively.
The idea would be to release this as v0.8.0. I'll then follow up with a new PR for v0.9.0 which will use v2 of `@dittolive/ditto` as a peer dependency.

Upgrade `@dittolive/ditto` peer dependency and replace `insert` with `upsert`

---

package.json
src/DittoProvider.spec.tsx
src/identity/useOfflinePlaygroundIdentity.spec.ts
src/identity/useOfflinePlaygroundIdentity.ts
src/mutations/useMutations.spec.tsx
src/mutations/useMutations.ts
src/queries/useLazyPendingCursorOperation.spec.tsx
src/queries/useLazyPendingCursorOperation.ts
src/queries/useLazyPendingIDSpecificOperation.spec.tsx
src/queries/useLazyPendingIDSpecificOperation.ts
src/queries/usePendingCursorOperation.spec.tsx
src/queries/usePendingCursorOperation.ts
src/queries/usePendingIDSpecificOperation.spec.tsx
src/queries/usePendingIDSpecificOperation.ts
src/useDitto.spec.tsx
yarn.lock

Related issue: #27
With v0.8.0 (65263cde1dec48298ab2046c9c5085298e0c8504) released for compatibility with `@dittolive/ditto` v1.1.10, we can now prepare for v0.9.0 to work with v2 of the JS SDK.
Besides breaking changes like `appName` -> `appID` and `_value` -> `value`, the biggest change in this PR is that our hooks are no longer generic over their document type which used to default to `DocumentLike` and allowed for `any`. The hooks now use the `Document` type directly instead.

Prepare for `@dittolive/ditto` v2

---

package.json
src/mutations/useMutations.spec.tsx
src/mutations/useMutations.ts
src/queries/useCollections.spec.tsx
src/queries/useLazyPendingIDSpecificOperation.spec.tsx
src/queries/usePendingCursorOperation.spec.tsx
src/queries/usePendingIDSpecificOperation.spec.tsx
yarn.lock

This PR switches to the stable v2 SDK and addresses type issues that came up when making the switch from the alpha version. After merging this, we should be able to release a stable v0.9.0 of `react-ditto`.
Changes:
- feat: upgrade `@dittolive/ditto` to v2.0.0
- fix: use `DocumentID` as ID type instead of `DocumentIDValue`

Use `@dittolive/ditto` v2 stable

---

examples/create-react-app-typescript-example/README.md

Updated the example README to include information about the [openssl change](https://nodejs.org/es/blog/release/v17.0.0/#openssl-3-0) on newer versions of node.

chore: update readme with openssl issue

---

README.md
src/identity/index.ts
src/identity/useOfflinePlaygroundIdentity.ts
src/identity/useOnlineIdentity.ts
src/identity/useOnlinePlaygroundIdentity.spec.ts
src/identity/useOnlinePlaygroundIdentity.ts

PR adds a new hook `useOnlinePlaygroundIdentity` for creating `onlinePlayground` identities. I opted for a separate hook mainly for three reasons:
1. Maintain the factory pattern we currently have for these hooks (i.e. all return 1 `create` function + optional utils)
2. So users of this library don't need to wrangle a return type like `IdentityOnlinePlayground | IdentityOnlineWithAuthentication`
3. Emphasize separation of `onlinePlayground` identity from `onlineWithAuthentication`, as it is not meant for production environments.
Resolves #31

feat: added hook for creating onlinePlayground identities

---

package.json
src/presence/useConnectionStatus.ts
src/queries/useRemotePeers.tsx
yarn.lock

This PR upgrades the `@dittolive/ditto` peer dependency to ^3.0.0 and replaces deprecated usages of `RemotePeer`, `PresenceConnectionType` and `observePeers`.
The plan would be to release this as a breaking change, i.e., v0.10.0, and then release and alpha version from #40 as another breaking change, i.e., v0.11.0-alpha.0.

feat!: upgrade `@dittolive/ditto` peer dependency to ^3.0.0

---

package.json
yarn.lock

This PR upgrades the `@dittolive/ditto` peer dependency to ^4.0.0-alpha2. I plan on releasing an alpha version from this after #39 is released.

feat!: upgrade `@dittolive/ditto` peer dependency to ^4.0.0-alpha2

---

README.md

We don't call `startSync` for the user from `react-ditto`, so adding it to the docs will make it clearer that they need to call it themselves.

docs: add `startSync` to ditto provider examples

---

package.json
yarn.lock

This PR upgrades the `@dittolive/ditto` peer dependency to ^4.0.0. The plan is to release v0.11.0 with this single change.

feat!: upgrade `@dittolive/ditto` peer dependency to ^4.0.0

---

package.json
src/queries/useVersion.ts
yarn.lock

Despite not being specified as a dependency in the `package.json` file,
we were still using `lodash` in `useVersion.ts`. To address this, we add
an explicit dependency on `lodash.isequal`, which is the only function
from `lodash` we need.

fix: remove implicit dependency on `lodash`

---

src/DittoProvider.spec.tsx
src/DittoProvider.tsx

Async setup functions are required to correctly await `ditto.disableSyncWithV3()`.
Required for #54 
To be merged with a merge commit.

feat: add support for async setup functions

---

CHANGELOG.md
README.md

I tried following the example and ran into some issues. Here, I have updated the Readme to fix these. 
- add correct imports
- fix syntax
- add reference to more information on specifying a web assembly module
- convert the example to use `onlinePlayground` which is preferred
- updates React syntax
- turns the example into a basic tasks app

chore: update `create-react-app` example in Readme

---

examples/vite-typescript-example/yarn.lock

There were a couple of lingering vulnerabilities in the example app which I missed from https://github.com/getditto/react-ditto/pull/68. I forgot this isn't a monorepo 😅 I went ahead and quickly patched them:
```bash
react-ditto/examples/vite-typescript-example on  al/fix-example-vulns [$] via  v20.9.0 
❯ yarn audit
yarn audit v1.22.22
0 vulnerabilities found - Packages audited: 753
✨  Done in 0.55s.
```

chore: fix vulnerabilities in example app
